.TH DWM 1 dwm\-VERSION
.SH NAME
dwm \- dynamic window manager (Seth Holland's build)
.SH SYNOPSIS
.B dwm
.RB [ \-v ]
.SH DESCRIPTION
dwm is a dynamic window manager for X.
.P
dwm "orders" windows based on recency and primacy, while dwm layouts may
change, the most recent "master" window is shown in the most prominent
position. There are bindings for cycling through and promoting windows to the
master position.
.P
Windows are grouped by tags. Each window can be tagged with one or multiple
tags. Selecting certain tags displays all windows with these tags.
.P
Each screen contains a small status bar which displays all available tags, the
layout, the title of the focused window, and the text read from the root window
name property, if the screen is focused. A floating window is indicated with an
empty square and a maximised floating window is indicated with a filled square
before the windows title.  The selected tags are indicated with a different
color. The tags of the focused window are indicated with a filled square in the
top left corner.  The tags which are applied to one or more windows are
indicated with an empty square in the top left corner.
.P
dwm draws a small border around windows to indicate the focus state.
.SH OPTIONS
.TP
.B \-v
prints version information to standard output, then exits.
.SH USAGE
.SS Status bar
.TP
.B X root window name
is read and displayed in the status text area. It can be set with the
.BR xsetroot (1)
command.
.TP
.B Left click
click on a tag label to display all windows with that tag, click on the layout
label toggles between tiled and floating layout.
.TP
.B Right click
click on a tag label adds/removes all windows with that tag to/from the view.
.TP
.B Super\-Left click
click on a tag label applies that tag to the focused window.
.TP
.B Super\-Right click
click on a tag label adds/removes that tag to/from the focused window.
.SS Keyboard commands
.TP
.B Super\-j/k
Focus next/previous window in stack.
.TP
.B Super\-m
Focus master window in stack.
.TP
.B Super\-Shift\-j/k
Push selected window down/up in stack.
.TP
.B Super\-Shift\-m
Push selected window to master position in stack.
.TP
.B Super\-[1..9]
View all windows with nth tag.
.TP
.B Control\-Shift\-[1..9]
View all windows with nth tag (alternative binding).
.TP
.B Super\-Control\-[1..9]
Toggle view of all windows with nth tag.
.TP
.B Super\-Shift\-[1..9]
Apply nth tag to focused window.
.TP
.B Super\-Control\-Shift\-[1..9]
Toggle nth tag on focused window.
.TP
.B Super\-0
View all windows with any tag.
.TP
.B Super\-Shift\-0
Apply all tags to focused window.
.TP
.B Super\-Tab
Toggles to the previously selected tags.
.TP
.B Super\-x
Close focused window.
.TP
.B Super\-o
Increase number of windows in master area.
.TP
.B Super\-Shift\-o
Decrease number of windows in master area.
.TP
.B Super\-a
Toggle gaps on/off.
.TP
.B Super\-Shift\-a
Reset gaps to default.
.TP
.B Super\-h
Decrease master area size.
.TP
.B Super\-l
Increase master area size.
.TP
.B Super\-Shift\-q
Quit dwm.
.TP
.B Super\-Return
Spawn terminal (alacritty).
.TP
.B Super\-space
Cycle to next layout.
.TP
.B Super\-Shift\-space
Cycle to previous layout.
.TP
.B Super\-Shift\-Return
Toggle scratchpad terminal (alacritty).
.TP
.B Super\-apostrophe
Toggle scratchpad calculator (python).
.TP
.B Super\-t
Toggle scratchpad translator (trans \-I ja:en).
.TP
.B Super\-Shift\-u
Toggle scratchpad units (units).
.TP
.B Super\-equal
Increase gaps size.
.TP
.B Super\-minus
Decrease gaps size.
.TP
.B Super\-b
Toggle status bar on/off.
.TP
.B Super\-Escape
Focus next monitor.
.TP
.B Super\-Left
Tag previous monitor.
.TP
.B Super\-Right
Tag next monitor.
.TP
.B Super\-F1
Toggle floating state of focused window.
.TP
.B Control\-F11
Toggle fullscreen state of focused window.
.TP
.B F13
Reload .Xresources.
.TP
.B Super\-Shift\-Alt\-Control\-F12
Reload .Xresources.
.SS Mouse commands
.TP
.B Super\-Left click
Move focused window while dragging. Tiled windows will be toggled to the floating state.
.TP
.B Super\-Middle click
Toggles focused window between floating and tiled state.
.TP
.B Super\-Right click
Resize focused window while dragging. Tiled windows will be toggled to the floating state.
.SH CUSTOMIZATION
dwm is customized by creating a custom config.h and (re)compiling the source
code. This keeps it fast, secure and simple.
.SH SIGNALS
.TP
.B SIGHUP - 1
Restart the dwm process.
.TP
.B SIGTERM - 15
Cleanly terminate the dwm process.
.SH SEE ALSO
.BR dmenu (1),
.BR st (1)
.SH ISSUES
Java applications which use the XToolkit/XAWT backend may draw grey windows
only. The XToolkit/XAWT backend breaks ICCCM-compliance in recent JDK 1.5 and early
JDK 1.6 versions, because it assumes a reparenting window manager. Possible workarounds
are using JDK 1.4 (which doesn't contain the XToolkit/XAWT backend) or setting the
environment variable
.BR AWT_TOOLKIT=MToolkit
(to use the older Motif backend instead) or running
.B xprop -root -f _NET_WM_NAME 32a -set _NET_WM_NAME LG3D
or
.B wmname LG3D
(to pretend that a non-reparenting window manager is running that the
XToolkit/XAWT backend can recognize) or when using OpenJDK setting the environment variable
.BR _JAVA_AWT_WM_NONREPARENTING=1 .
.SH BUGS
Send all bug reports with a patch to hackers@suckless.org.
